-- Base de Datos de Hospital Regional de Talca

-- Creación de la base de datos
CREATE DATABASE IF NOT EXISTS inventario_hrt;
USE inventario_hrt;

-- Tabla BODEGA
CREATE TABLE BODEGA (
    ID_LOTE INT NOT NULL,
    CANTIDAD_DISPONIBLE INTEGER NOT NULL,
    PRIMARY KEY (ID_LOTE)
);

-- Tabla CLASIFICACION
CREATE TABLE CLASIFICACION (
    ID_CLASIFICACION INT AUTO_INCREMENT NOT NULL,
    NOMBRE_CLASIFICACION VARCHAR(50) NOT NULL,
    DIAS_ABERTURA_CLASIFICACION INT NOT NULL,
    UNIDAD_CONTENIDO_CLASIFICACION VARCHAR(50) NOT NULL,
    ESTADO_CLASIFICACION TINYINT NOT NULL,
    PRIMARY KEY (ID_CLASIFICACION)
);

-- Tabla DISPONIBILIDAD
CREATE TABLE DISPONIBILIDAD (
    ID_DISPONIBILIDAD INT AUTO_INCREMENT NOT NULL,
    NOMBRE_DISPONIBILIDAD VARCHAR(100) NOT NULL,
    ESTADO_DISPONIBILIDAD TINYINT NOT NULL,
    PRIMARY KEY (ID_DISPONIBILIDAD)
);

-- Tabla PROCEDENCIA
CREATE TABLE PROCEDENCIA (
    ID_PROCEDENCIA INT AUTO_INCREMENT NOT NULL,
    NOMBRE_PROCEDENCIA VARCHAR(100) NOT NULL,
    ESTADO_PROCEDENCIA INT NOT NULL,
    PRIMARY KEY (ID_PROCEDENCIA)
);

-- Tabla PACIENTE
CREATE TABLE PACIENTE (
    ID_PACIENTE INT NOT NULL,
    RUT_PACIENTE INT NOT NULL,
    NOMBRE_PACIENTE VARCHAR(100) NOT NULL,
    APATERNO_PACIENTE VARCHAR(100) NOT NULL,
    AMATERNO_PACIENTE VARCHAR(100) NOT NULL,
    FECHA_NACIMIENTO DATE,
    PRIMARY KEY (ID_PACIENTE)
);

-- Tabla PERFIL
CREATE TABLE PERFIL (
    ID_PERFIL INT AUTO_INCREMENT NOT NULL,
    NOMBRE_PERFIL VARCHAR(50) NOT NULL,
    ESTADO_PERFIL TINYINT NOT NULL,
    PRIMARY KEY (ID_PERFIL)
);

-- Tabla PROVEEDOR
CREATE TABLE PROVEEDOR (
    ID_PROVEEDOR INT NOT NULL,
    NOMBRE_PROVEEDOR VARCHAR(100) NOT NULL,
    CONTACTO_PROVEEDOR INT NOT NULL,
    CORREO_PROVEEDOR VARCHAR(100),
    ESTADO_PROVEEDOR TINYINT NOT NULL,
    PRIMARY KEY (ID_PROVEEDOR)
);

-- Tabla ESTADO_SOLICITUD
CREATE TABLE ESTADO_SOLICITUD (
    ID_ESTADO_SOLICITUD INT AUTO_INCREMENT NOT NULL,
    NOMBRE_ESTADO_SOLICITUD VARCHAR(100) NOT NULL,
    ESTADO_SOLICITUD INT NOT NULL,
    PRIMARY KEY (ID_ESTADO_SOLICITUD)
);

-- Tabla SUBUNIDAD
CREATE TABLE SUBUNIDAD (
    ID_SUBUNIDAD INT AUTO_INCREMENT NOT NULL,
    NOMBRE_SUBUNIDAD VARCHAR(100) NOT NULL,
    RESPONSABLE_SUBUNIDAD VARCHAR(100) NOT NULL,
    ESTADO_SUBUNIDAD TINYINT NOT NULL,
    PRIMARY KEY (ID_SUBUNIDAD)
);

-- Tabla TIPO_COMPRA
CREATE TABLE TIPO_COMPRA (
    ID_TIPO_COMPRA INT AUTO_INCREMENT NOT NULL,
    NOMBRE_TIPO_COMPRA VARCHAR(100) NOT NULL,
    ESTADO_TIPO_COMPRA TINYINT NOT NULL,
    PRIMARY KEY (ID_TIPO_COMPRA)
);

-- Tabla TIPO_MOVIMIENTO_HISTORIAL
CREATE TABLE TIPO_MOVIMIENTO_HISTORIAL (
    ID_TIPO_MOVIMIENTO INT AUTO_INCREMENT NOT NULL,
    NOMBRE_TIPO_MOVIMIENTO VARCHAR(100) NOT NULL,
    ESTADO_TIPO_MOVIMIENTO INT NOT NULL,
    PRIMARY KEY (ID_TIPO_MOVIMIENTO)
);

-- Tabla TIPO_REGISTRO
CREATE TABLE TIPO_REGISTRO (
    ID_TIPO_REGISTRO INT AUTO_INCREMENT NOT NULL,
    NOMBRE_TIPO_REGISTRO VARCHAR(100) NOT NULL,
    ESTADO_TIPO_REGISTRO TINYINT NOT NULL,
    PRIMARY KEY (ID_TIPO_REGISTRO)
);

-- Tabla ESTAMENTO
CREATE TABLE ESTAMENTO (
    ID_ESTAMENTO INT AUTO_INCREMENT NOT NULL,
    NOMBRE_ESTAMENTO VARCHAR(100) NOT NULL,
    SUELDO_HORA_ESTAMENTO INT NOT NULL,
    ESTADO_ESTAMENTO TINYINT NOT NULL,
    PRIMARY KEY (ID_ESTAMENTO)
);

-- Tabla TIPO_MANTENCION
CREATE TABLE TIPO_MANTENCION (
    ID_TIPO_MANTENCION INT AUTO_INCREMENT NOT NULL,
    NOMBRE_TIPO_MANTENCION VARCHAR(100) NOT NULL,
    ESTADO_TIPO_MANTENCION TINYINT NOT NULL,
    PRIMARY KEY (ID_TIPO_MANTENCION)
);

-- Tabla PROCEDIMIENTO
CREATE TABLE PROCEDIMIENTO (
    ID_PROCEDIMIENTO INT NOT NULL,
    NOMBRE_PROCEDIMIENTO VARCHAR(500) NOT NULL,
    ESTADO_PROCEDIMIENTO TINYINT NOT NULL,
    PRIMARY KEY (ID_PROCEDIMIENTO)
);

-- Tabla CONDICION_PACIENTE
CREATE TABLE CONDICION_PACIENTE (
    ID_CONDICION_PACIENTE INT AUTO_INCREMENT NOT NULL,
    NOMBRE_CONDICION_PACIENTE VARCHAR(100) NOT NULL,
    ESTADO_CONDICION_PACIENTE TINYINT NOT NULL,
    PRIMARY KEY (ID_CONDICION_PACIENTE)
);

-- Tabla EQUIPO_MEDICO
CREATE TABLE EQUIPO_MEDICO (
    ID_EQUIPO_MEDICO INT AUTO_INCREMENT NOT NULL,
    NUM_SERIE_EQUIPO VARCHAR(100) NOT NULL,
    NOMBRE_EQUIPO VARCHAR(500) NOT NULL,
    MARCA_EQUIPO VARCHAR(100) NOT NULL,
    VALOR_HORA INT,
    VIDA_UTIL_EQUIPO INT NOT NULL,
    FECHA_ADQUISICION_EQUIPO DATE NOT NULL,
    ESTADO_EQUIPO TINYINT NOT NULL,
    OBSERVACION_EQUIPO TEXT,
    PRIMARY KEY (ID_EQUIPO_MEDICO)
);

-- Tabla INSUMO
CREATE TABLE INSUMO (
    ID_INSUMO INT AUTO_INCREMENT NOT NULL,
    CODIGO_ABAS_INSUMO VARCHAR(100) NOT NULL,
    NOMBRE_INSUMO VARCHAR(100) NOT NULL,
    ESTADO_INSUMO TINYINT NOT NULL,
    ID_CLASIFICACION_INSUMO INT NOT NULL,
    ID_DISPONIBILIDAD_INSUMO INT NOT NULL,
    PRIMARY KEY (ID_INSUMO),
    FOREIGN KEY (ID_CLASIFICACION_INSUMO) REFERENCES CLASIFICACION(ID_CLASIFICACION),
    FOREIGN KEY (ID_DISPONIBILIDAD_INSUMO) REFERENCES DISPONIBILIDAD(ID_DISPONIBILIDAD)
);

-- Tabla LICITACION
CREATE TABLE LICITACION (
    ID_LICITACION INT AUTO_INCREMENT NOT NULL,
    ID_PUBLICO_LICITACION VARCHAR(100) NOT NULL,
    NOMBRE_LICITACION VARCHAR(100) NOT NULL,
    RESOLUCION_EXENTA INT NOT NULL,
    REFERENCIA INT NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    MONTO_LICITADO INT NOT NULL,
    ID_PROVEEDOR_LICITACION INT NOT NULL,
    ID_INSUMO_LICITACION INT NOT NULL,
    PRIMARY KEY (ID_LICITACION),
    FOREIGN KEY (ID_PROVEEDOR_LICITACION) REFERENCES PROVEEDOR(ID_PROVEEDOR),
    FOREIGN KEY (ID_INSUMO_LICITACION) REFERENCES INSUMO(ID_INSUMO)
);

-- Tabla LOTE
CREATE TABLE LOTE (
    ID_LOTE INT NOT NULL,
    MARCA_LOTE VARCHAR(50) NOT NULL,
    CODIGO_PRODUCTO_LOTE VARCHAR(100) NOT NULL,
    UNIDAD_ABAS_LOTE VARCHAR(50) NOT NULL,
    CANTIDAD_TOTAL_LOTE INT NOT NULL,
    COSTO_UNITARIO_LOTE INT NOT NULL,
    FECHA_VENCIMIENTO DATE NOT NULL,
    ID_INSUMO_LOTE INT NOT NULL,
    ID_PROVEEDOR_LOTE INT NOT NULL,
    ID_PROCEDENCIA_LOTE INT NOT NULL,
    ID_TIPO_COMPRA_LOTE INT NOT NULL,
    OBSERVACION_LOTE TEXT,
    PRIMARY KEY (ID_LOTE),
    FOREIGN KEY (ID_INSUMO_LOTE) REFERENCES INSUMO(ID_INSUMO),
    FOREIGN KEY (ID_PROVEEDOR_LOTE) REFERENCES PROVEEDOR(ID_PROVEEDOR),
    FOREIGN KEY (ID_PROCEDENCIA_LOTE) REFERENCES PROCEDENCIA(ID_PROCEDENCIA),
    FOREIGN KEY (ID_TIPO_COMPRA_LOTE) REFERENCES TIPO_COMPRA(ID_TIPO_COMPRA)
);

-- Tabla SALA
CREATE TABLE SALA (
    ID_SALA INT AUTO_INCREMENT NOT NULL,
    NUMERO_SALA VARCHAR(50) NOT NULL,
    NOMBRE_SALA VARCHAR(100) NOT NULL,
    ESTADO_SALA TINYINT NOT NULL,
    ID_SUBUNIDAD_SALA INT NOT NULL,
    PRIMARY KEY (ID_SALA),
    FOREIGN KEY (ID_SUBUNIDAD_SALA) REFERENCES SUBUNIDAD(ID_SUBUNIDAD)
);

-- Tabla INSUMO_SALA
CREATE TABLE INSUMO_SALA (
    ID_INSUMO_SALA INT AUTO_INCREMENT NOT NULL,
    CANTIDAD_INSUMO_SALA INT NOT NULL,
    ID_LOTE_INSUMO_SALA INT NOT NULL,
    ID_SALA_INSUMO_SALA INT NOT NULL,
    PRIMARY KEY (ID_INSUMO_SALA),
    FOREIGN KEY (ID_LOTE_INSUMO_SALA) REFERENCES LOTE(ID_LOTE),
    FOREIGN KEY (ID_SALA_INSUMO_SALA) REFERENCES SALA(ID_SALA)
);

-- Tabla USUARIO (MODIFICADA)
CREATE TABLE USUARIO (
    ID_USUARIO INT AUTO_INCREMENT NOT NULL,  -- Ahora es autoincremental
    NOMBRE_USUARIO VARCHAR(100) NOT NULL,
    RUT_USUARIO VARCHAR(12) NOT NULL,        -- Nuevo campo RUT
    CORREO_USUARIO VARCHAR(100),
    CONTRASENA_USUARIO VARCHAR(255) NOT NULL,
    ID_PERFIL_USUARIO INT NOT NULL,
    ID_ESTAMENTO_USUARIO INT NOT NULL,
    PRIMARY KEY (ID_USUARIO),
    UNIQUE (RUT_USUARIO),                    -- RUT único
    FOREIGN KEY (ID_PERFIL_USUARIO) REFERENCES PERFIL(ID_PERFIL),
    FOREIGN KEY (ID_ESTAMENTO_USUARIO) REFERENCES ESTAMENTO(ID_ESTAMENTO)
);

-- Tabla SOLICITUD
CREATE TABLE SOLICITUD (
    ID_SOLICITUD INT AUTO_INCREMENT NOT NULL,
    FECHA_SOLICITUD TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ID_USUARIO_SOLICITUD INT NOT NULL,
    ID_SALA_SOLICITUD INT NOT NULL,
    ID_ESTADO_SOLICITUD_INS INT NOT NULL,
    PRIMARY KEY (ID_SOLICITUD),
    FOREIGN KEY (ID_USUARIO_SOLICITUD) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_SALA_SOLICITUD) REFERENCES SALA(ID_SALA),
    FOREIGN KEY (ID_ESTADO_SOLICITUD_INS) REFERENCES ESTADO_SOLICITUD(ID_ESTADO_SOLICITUD)
);

-- Tabla DETALLE_SOLICITUD
CREATE TABLE DETALLE_SOLICITUD (
    ID_DETALLE_SOLICITUD INT AUTO_INCREMENT NOT NULL,
    CANTIDAD INT NOT NULL,
    ID_SOLICITUD_DE INT NOT NULL,
    ID_INSUMO_DE INT NOT NULL,
    PRIMARY KEY (ID_DETALLE_SOLICITUD),
    FOREIGN KEY (ID_SOLICITUD_DE) REFERENCES SOLICITUD(ID_SOLICITUD),
    FOREIGN KEY (ID_INSUMO_DE) REFERENCES INSUMO(ID_INSUMO)
);

-- Tabla USO_PACIENTE
CREATE TABLE USO_PACIENTE (
    ID_USO_PACIENTE INT AUTO_INCREMENT NOT NULL,
    CANTIDAD_UTILIZADA_USO INT NOT NULL,
    FECHA_USO DATE NOT NULL,
    ID_SALA_USO INT NOT NULL,
    ID_INSUMO_SALA_USO INT NOT NULL,
    ID_PACIENTE_USO INT NOT NULL,
    ID_TIPO_REGISTRO_USO INT NOT NULL,
    PRIMARY KEY (ID_USO_PACIENTE),
    FOREIGN KEY (ID_SALA_USO) REFERENCES SALA(ID_SALA),
    FOREIGN KEY (ID_INSUMO_SALA_USO) REFERENCES INSUMO_SALA(ID_INSUMO_SALA),
    FOREIGN KEY (ID_PACIENTE_USO) REFERENCES PACIENTE(ID_PACIENTE),
    FOREIGN KEY (ID_TIPO_REGISTRO_USO) REFERENCES TIPO_REGISTRO(ID_TIPO_REGISTRO)
);

-- Tabla PRESTACION
CREATE TABLE PRESTACION (
    ID_PRESTACION INT AUTO_INCREMENT NOT NULL,
    FECHA_PRESTACION DATE NOT NULL,
    HORA_INICIO TIME NOT NULL,
    HORA_FIN TIME NOT NULL,
    COSTO_TOTAL_PRESTACION INT,
    HORAS_TRABAJADAS DECIMAL(5,2),
    COSTO_USUARIO INT,
    ID_PROCEDIMIENTO_PRES INT NOT NULL,
    ID_CONDICION_PACIENTE_PRES INT NOT NULL,
    ID_PACIENTE_PRES INT NOT NULL,
    ID_SALA_PRES INT NOT NULL,
    PRIMARY KEY (ID_PRESTACION),
    FOREIGN KEY (ID_PROCEDIMIENTO_PRES) REFERENCES PROCEDIMIENTO(ID_PROCEDIMIENTO),
    FOREIGN KEY (ID_CONDICION_PACIENTE_PRES) REFERENCES CONDICION_PACIENTE(ID_CONDICION_PACIENTE),
    FOREIGN KEY (ID_PACIENTE_PRES) REFERENCES PACIENTE(ID_PACIENTE),
    FOREIGN KEY (ID_SALA_PRES) REFERENCES SALA(ID_SALA)
);

-- Tabla PRESTACION_LOTE
CREATE TABLE PRESTACION_LOTE (
    ID_PRESTACION_LOTE INT AUTO_INCREMENT NOT NULL,
    ID_PRESTACION_LT INT NOT NULL,
    ID_LOTE_LT INT NOT NULL,
    CANTIDAD_UTILIZADA INT NOT NULL,
    COSTO_LT INT,
    PRIMARY KEY (ID_PRESTACION_LOTE),
    FOREIGN KEY (ID_PRESTACION_LT) REFERENCES PRESTACION(ID_PRESTACION),
    FOREIGN KEY (ID_LOTE_LT) REFERENCES LOTE(ID_LOTE)
);

-- Tabla PRESTACION_USUARIO
CREATE TABLE PRESTACION_USUARIO (
    ID_PRESTACION_USUARIO INT AUTO_INCREMENT NOT NULL,
    ID_PRESTACION_USU INT NOT NULL,
    ID_USUARIO_USU INT NOT NULL,
    PRIMARY KEY (ID_PRESTACION_USUARIO),
    FOREIGN KEY (ID_PRESTACION_USU) REFERENCES PRESTACION(ID_PRESTACION),
    FOREIGN KEY (ID_USUARIO_USU) REFERENCES USUARIO(ID_USUARIO)
);

-- Tabla PRESTACION_EQUIPO
CREATE TABLE PRESTACION_EQUIPO (
    ID_PRESTACION_EQUIPO INT AUTO_INCREMENT NOT NULL,
    ID_PRESTACION_EQU INT NOT NULL,
    ID_EQUIPO_MEDICO_PRE INT NOT NULL,
    PRIMARY KEY (ID_PRESTACION_EQUIPO),
    FOREIGN KEY (ID_PRESTACION_EQU) REFERENCES PRESTACION(ID_PRESTACION),
    FOREIGN KEY (ID_EQUIPO_MEDICO_PRE) REFERENCES EQUIPO_MEDICO(ID_EQUIPO_MEDICO)
);

-- Tabla MANTENCION_EQUIPO
CREATE TABLE MANTENCION_EQUIPO (
    ID_MANTENCION INT AUTO_INCREMENT NOT NULL,
    ID_EQUIPO_MEDICO_ME INT NOT NULL,
    ID_TIPO_MANTENCION_ME INT NOT NULL,
    FECHA_MANTENCION DATE NOT NULL,
    PROXIMA_MANTENCION DATE,
    RESPONSABLE_MANTENCION VARCHAR(100) NOT NULL,
    COSTO_MANTENCION INT NOT NULL,
    DESCRIPCION_MANTENCION TEXT NOT NULL,
    PERIOCIDAD_MANTENCION INT NOT NULL,
    PRIMARY KEY (ID_MANTENCION),
    FOREIGN KEY (ID_EQUIPO_MEDICO_ME) REFERENCES EQUIPO_MEDICO(ID_EQUIPO_MEDICO),
    FOREIGN KEY (ID_TIPO_MANTENCION_ME) REFERENCES TIPO_MANTENCION(ID_TIPO_MANTENCION)
);

-- Tabla HISTORIAL_MOVIMIENTOS
CREATE TABLE HISTORIAL_MOVIMIENTOS (
    ID_MOVIMIENTO INT AUTO_INCREMENT NOT NULL,
    CANTIDAD INT NOT NULL,
    FECHA_MOVIMIENTO DATE,
    ID_USUARIO_HISTORIAL INT NOT NULL,
    ID_TIPO_MOVIMIENTO_HISTORIAL INT NOT NULL,
    ID_LOTE_HISTORIAL INT NOT NULL,
    PRIMARY KEY (ID_MOVIMIENTO),
    FOREIGN KEY (ID_USUARIO_HISTORIAL) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_TIPO_MOVIMIENTO_HISTORIAL) REFERENCES TIPO_MOVIMIENTO_HISTORIAL(ID_TIPO_MOVIMIENTO),
    FOREIGN KEY (ID_LOTE_HISTORIAL) REFERENCES LOTE(ID_LOTE)
);


CREATE TABLE IF NOT EXISTS TRAZABILIDAD_ACCION (
    ID_TRAZABILIDAD INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,             -- Usuario que realizó la acción
    ID_INSUMO INT NOT NULL,              -- Insumo afectado
    CANTIDAD INT DEFAULT NULL,           -- Cantidad relacionada (puede ser NULL si no aplica)
    ACCION VARCHAR(50) NOT NULL,         -- Ej: 'Ingreso', 'Retiro', 'Uso', etc.
    FECHA_ACCION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_INSUMO) REFERENCES INSUMO(ID_INSUMO)
);

----------------- Triggers -----------------

-- Calcular Horas Trabajadas
DELIMITER //
CREATE TRIGGER trg_calcular_horas_trabajadas
BEFORE INSERT ON PRESTACION
FOR EACH ROW
BEGIN
    SET NEW.HORAS_TRABAJADAS = TIMESTAMPDIFF(MINUTE, NEW.HORA_INICIO, NEW.HORA_FIN) / 60;
END;
//
DELIMITER ;

-- Actualizar Horas Trabajadas
DELIMITER //
CREATE TRIGGER trg_update_horas_trabajadas
BEFORE UPDATE ON PRESTACION
FOR EACH ROW
BEGIN
    IF OLD.HORA_INICIO <> NEW.HORA_INICIO OR OLD.HORA_FIN <> NEW.HORA_FIN THEN
        SET NEW.HORAS_TRABAJADAS = TIMESTAMPDIFF(MINUTE, NEW.HORA_INICIO, NEW.HORA_FIN) / 60;
    END IF;
END;
//
DELIMITER ;